"""add openai anthropic key columns to users

Revision ID: 3d05b628f4fa
Revises: 1b9a8a15f94e
Create Date: 2026-05-20 10:17:00.948935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '3d05b628f4fa'
down_revision: Union[str, Sequence[str], None] = '1b9a8a15f94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openai_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('anthropic_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anthropic_api_key')
    op.drop_column('users', 'openai_api_key')
    # ### end Alembic commands ###
