"""update embedding dimension to 768

Revision ID: 5708d54826a0
Revises: 707fee62d7e9
Create Date: 2026-05-18 18:07:19.329815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '5708d54826a0'
down_revision: Union[str, Sequence[str], None] = '707fee62d7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_cache', 'prompt_embedding',
               existing_type=Vector(1536),
               type_=Vector(768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_cache', 'prompt_embedding',
               existing_type=Vector(768),
               type_=Vector(1536),
               existing_nullable=False)
    # ### end Alembic commands ###
