"""update embedding dimension to 3072

Revision ID: a2dd1efd43a2
Revises: 7b97da4155ae
Create Date: 2026-05-18 18:14:30.842722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a2dd1efd43a2'
down_revision: Union[str, Sequence[str], None] = '7b97da4155ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt_embedding', Vector(3072), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_cache')
    # ### end Alembic commands ###
