"""add prompt and response text to inference logs

Revision ID: c9507429283f
Revises: 426404e5bbde
Create Date: 2026-05-20 01:25:25.946912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9507429283f'
down_revision: Union[str, Sequence[str], None] = '426404e5bbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_logs', sa.Column('prompt_text', sa.Text(), nullable=True))
    op.add_column('inference_logs', sa.Column('response_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inference_logs', 'response_text')
    op.drop_column('inference_logs', 'prompt_text')
    # ### end Alembic commands ###
