"""add gemini_api_key to users

Revision ID: cda121ffcaec
Revises: d5de02a0a0da
Create Date: 2026-05-20 00:06:04.322910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'cda121ffcaec'
down_revision: Union[str, Sequence[str], None] = 'd5de02a0a0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gemini_api_key')
    # ### end Alembic commands ###
