"""add users table and update api_keys

Revision ID: d5de02a0a0da
Revises: 707fee62d7e9
Create Date: 2026-05-19 23:44:11.482939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from pgvector.sqlalchemy import Vector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'd5de02a0a0da'
down_revision: Union[str, Sequence[str], None] = '707fee62d7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('api_keys', sa.Column('key', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.create_unique_constraint(None, 'api_keys', ['key'])
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    op.drop_column('api_keys', 'key_hash')
    op.add_column('inference_logs', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'inference_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inference_logs', type_='foreignkey')
    op.drop_column('inference_logs', 'user_id')
    op.add_column('api_keys', sa.Column('key_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_keys', 'user_id')
    op.drop_column('api_keys', 'key')
    op.drop_table('users')
    # ### end Alembic commands ###
